---
- name: Create a file using Ansible
  hosts: 192.168.88.244
  become: false

  tasks:
    - name: Create a file
      ansible.builtin.file:
        path: /home/fintech/awx_edit.txt
        state: touch
