---
- name: Install Nginx
  hosts: 192.168.88.244
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: enable nginx
      command: systemctl enable nginx
      command: systemctl start nginx
      become: yes
