---
- name: Install Nginx
  hosts: 192.168.88.244
  become: true
  tasks:
    - name: Update the system
      command: apt update && apt upgrade        
    - name: Install Nginx
      apt:
        name: Nginx
        state: present

    - name: enable nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
