---
- name: Install Nginx
  hosts: 192.168.88.244
  become: true
  tasks:
    - name: Update the system
      apt:
        update_cache: yes
        become: true

    - name: Install Nginx
      apt:
        name: Nginx
        state: present
        become: true

    - name: enable nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
        become: true
