---
- name: Update repository cache on Ubuntu servers
  hosts: 192.168.88.248
  become: yes  # This allows the playbook to run with sudo privileges
  become_user: root
  tasks:
    - name: Update repository cache
      command: apt-get update >> /root/update_output.txt
