---
- name: Update repository cache on Ubuntu servers
  hosts: 192.168.88.248
  become: yes  # This allows the playbook to run with sudo privileges
  become_user: root
  tasks:
    - name: Update repository cache
      apt:
        update_cache: yes
      register: apt_output
    
    - name: Document output
      copy:
        content: "{{ apt_output.stdout | join('\n') }}"
        dest: /root/apt_output.txt
