---
- name: Update repository cache on Ubuntu servers
  hosts: Admin_Server
  become: yes  # This allows the playbook to run with sudo privileges
  become_user: root
  gather_facts: true
  tasks:
    - name: Update repository cache
      command: sudo apt update
      register: apt_output
      args:
        warn: false
    
    - name: Document output
      copy:
        content: "{{ apt_output.stdout | default('') }}{{ apt_output.stderr | default('') }}"
        dest: "/root/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}_output.txt"



