---
- name: Update repository cache on Ubuntu servers
  hosts: Admin_Server
  become: yes  
  become_user: root
  gather_facts: true
  tasks:
    - name: Creating a directory for storing the log of update command 
      file:
        path: /var/log/update_log
        state: directory
      become: yes
        
    - name: Update repository cache
      command: sudo apt update
      register: apt_output
      args:
        warn: false
    
    - name: Storing the stdout or stderr in /var/log with date and time.
      copy:
        content: "{{ apt_output.stdout | default('') }}{{ apt_output.stderr | default('') }}"
        dest: "/var/log/update_log/{{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic_short }}_output.txt"
      become: yes

    - name: find the log files
      - find: 
          paths: /var/log/update_log/
          recurse: no
          patterns: *.txt
        register: logs_to_copy

    - name: fetch the log folder to the ansible master server.
      - fetch:
          src: {{ item.path }}
          dest: /home/update_log/
          flat: yes
        with_items: "{{ logs_to_copy.files }}"
        become: yes



