---
- name: Update repository cache on Ubuntu servers
  hosts: Admin_Server
  become: yes  # This allows the playbook to run with sudo privileges
  become_user: root
  gather_facts: true
  tasks:
    - name: Creating a directory for storing the log of update command 
      file:
        path: /var/log/update_log
        state: directory
      become: yes
        
    - name: Update repository cache
      command: sudo apt update
      register: apt_output
      args:
        warn: false
    
    - name: Storing the stdout or stderr in /var/log with date and time.
      copy:
        content: "{{ apt_output.stdout | default('') }}{{ apt_output.stderr | default('') }}"
        dest: "/var/log/update_log/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}_output.txt"
      become: yes

    - name: rsync the log folder to the ansible master server.
      fetch:
        src: /var/log/update_log/Admin_Server_2024-03-18_11:19:49_output.txt
        dest: /home/fintech/update_log/
        flat: no
        force: no
      become: yes




