---
- name: Update repository cache on Ubuntu servers
  hosts: 192.168.88.248
  become: yes  # This allows the playbook to run with sudo privileges
  become_user: root
  tasks:
    - name: Update repository cache
      command: apt update
      register: apt_output
      args:
        warn: false
    
    - name: Document output
      copy:
        content: "{{ apt_output.stdout | default('') }}{{ apt_output.stderr | default('') }}"
        dest: /root/apt_output.txt
